### ISSUE TITLE
Error about run train_net.py

### ISSUE THREAD

**Issue by LZL-CS** [rakhimovv/npbgpp#10]
Hi, thanks for your wonderful work. When I run train_net.py use the command line, I got the error:

> python train_net.py trainer.gpus=1 hydra.run.dir=experiments/npbgpp_scannet datasets=scannet_pretrain datasets.n_point=6e6 system=npbgpp_sphere system.visibility_scale=0.5 trainer.max_epochs=39 dataloader.train_data_mode=each trainer.reload_dataloaders_every_n_epochs=1
In 'config': Could not find 'trainer/project'
Config search path:
        provider=hydra, path=pkg://hydra.conf
        provider=main, path=file:///public/home/luanzl/WorkSpace/npbgpp/configs
        provider=schema, path=structured://
Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

By the way, when I try to debug  train_net.py on Pycharm IDE  in a remote server step-by-step, I got the error:

> hydra.errors.MissingConfigException: In 'config': Could not find 'trainer/project'
Config search path:
	provider=hydra, path=pkg://hydra.conf
	provider=main, path=file:///public/home/luanzl/WorkSpace/npbgpp/configs
	provider=schema, path=structured://

I think it's due to the **config.yaml** file error, which is related to `trainer: project`

May I know how can I resolve these issues? Thanks in advance!

**Comment by rakhimovv** [comment]
Hello @LZL-CS ! I think your IDE deleted unused imports in `train_net.py` especially:

`from configs import trainer_conf`

Without this line the error appears

**Comment by LZL-CS** [comment]
Thanks for your reply, I will check this.

**Comment by LZL-CS** [comment]
May I know can npbgpp apply to the outdoor scene such as the KITTI dataset for the novel view synthesis?

**Comment by rakhimovv** [comment]
Probably. First of all, there is no background modeling in npbg++, so there is no guarantee to have a good image result in picture areas where there is no points, e.g. sky. And second, current software implementation does not support a big amount of points, e.g. larger than 6e6 (on 1080Ti), but it is possible after careful code modification.

**Comment by LZL-CS** [comment]
Hi @rakhimovv, got it, thanks for your reply.
