### ISSUE TITLE
Can you provide a Docker environment?

### ISSUE THREAD

**Issue by Dongber** [rakhimovv/npbgpp#11]
I encountered difficulties when configuring the environment according to the Readme using the A100 GPU. Can you please provide a Dockerfile or a repository link for the Docker image?

**Comment by rakhimovv** [comment]
Hello @Dongber! I used the following:

```
FROM nvidia/cudagl:11.4.2-devel-ubuntu20.04

ENV PIP_NO_CACHE_DIR=1 \
    LANG=C.UTF-8 \
    LC_ALL=C.UTF-8 \
    DEBIAN_FRONTEND=noninteractive

RUN apt-get clean \
 && apt-get update -qq \
 && apt-get install -y --no-install-recommends \
    python3-opencv \
    ca-certificates \
    python3-dev \
    git \
    wget \
    sudo \
    ninja-build \
    curl \
    build-essential \
    software-properties-common \
    htop \
    unzip \
    unrar \
    tree \
    vim \
    tmux \
    rsync \
    ffmpeg \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

RUN ln -sv /usr/bin/python3 /usr/bin/python

RUN wget --quiet https://bootstrap.pypa.io/pip/3.6/get-pip.py -O ~/get-pip.py && \
    python3 ~/get-pip.py && \
    rm ~/get-pip.py

ARG TORCH_CUDA_ARCH_LIST="Kepler;Kepler+Tesla;Maxwell;Maxwell+Tegra;Pascal;Volta;Turing"
ENV TORCH_CUDA_ARCH_LIST="${TORCH_CUDA_ARCH_LIST}"
ENV FORCE_CUDA="1"
RUN echo "export TORCH_CUDA_ARCH_LIST=\"Kepler;Kepler+Tesla;Maxwell;Maxwell+Tegra;Pascal;Volta;Turing\" " >> ~/.profile
RUN echo "export FORCE_CUDA=\"1\" " >> ~/.profile
```

but on my cluster I converted the docker image to singularity first and then just follow instructions in README.

Try to provide more details if there are further difficulties

**Comment by Dongber** [comment]
Dear rakhimovv,


I would like to thank you for your previous help with my code. I was able to successfully run it without any issues.


However, I have encountered a new question regarding data augmentation. I can't find apparent entry point for data loading in the code. I was wondering if you used any data augmentation techniques during the training process?


I apologize for my lack of knowledge in PyTorch Lightning. The encapsulated structure is still new to me, and I am still trying to get the hang of it. I would greatly appreciate it if you could provide me with some insights or directions on how to approach this issue.


Thank you for your time and consideration. I look forward to hearing from you soon.


Best regards





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rakhimovv/npbgpp"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月28日(星期二) 晚上8:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [rakhimovv/npbgpp] Can you provide a Docker environment? (Issue #11)





 
Hello @Dongber! I used the following:
 FROM nvidia/cudagl:11.4.2-devel-ubuntu20.04 ENV PIP_NO_CACHE_DIR=1 \     LANG=C.UTF-8 \     LC_ALL=C.UTF-8 \     DEBIAN_FRONTEND=noninteractive RUN apt-get clean \  &amp;&amp; apt-get update -qq \  &amp;&amp; apt-get install -y --no-install-recommends \     python3-opencv \     ca-certificates \     python3-dev \     git \     wget \     sudo \     ninja-build \     curl \     build-essential \     software-properties-common \     htop \     unzip \     unrar \     tree \     vim \     tmux \     rsync \     ffmpeg \  &amp;&amp; apt-get clean \  &amp;&amp; rm -rf /var/lib/apt/lists/* RUN ln -sv /usr/bin/python3 /usr/bin/python RUN wget --quiet https://bootstrap.pypa.io/pip/3.6/get-pip.py -O ~/get-pip.py &amp;&amp; \     python3 ~/get-pip.py &amp;&amp; \     rm ~/get-pip.py ARG TORCH_CUDA_ARCH_LIST="Kepler;Kepler+Tesla;Maxwell;Maxwell+Tegra;Pascal;Volta;Turing" ENV TORCH_CUDA_ARCH_LIST="${TORCH_CUDA_ARCH_LIST}" ENV FORCE_CUDA="1" RUN echo "export TORCH_CUDA_ARCH_LIST=\"Kepler;Kepler+Tesla;Maxwell;Maxwell+Tegra;Pascal;Volta;Turing\" " &gt;&gt; ~/.profile RUN echo "export FORCE_CUDA=\"1\" " &gt;&gt; ~/.profile  
but on my cluster I converted the docker image to singularity first and then just follow instructions in README.
 
Try to provide more details if there are further difficulties

**Comment by rakhimovv** [comment]
Hi @Dongber 

yes, there is data augmentation: first, nearby view are selected randomly, second there is a color augmentation
https://github.com/rakhimovv/npbgpp/blob/main/configs/system/npbgpp_sphere.yaml#L18
https://github.com/rakhimovv/npbgpp/blob/main/npbgplusplus/modeling/system/npbgpp.py#L276

Yes, the code structure is unfortunately quite complicated, but to start with:

anything regarding dataloaders one can find here
https://github.com/rakhimovv/npbgpp/blob/main/npbgplusplus/modeling/system/base.py#L569

If you have a specific scenario of what you would like to modify maybe I can help to show some direction
