### ISSUE TITLE
Question about how to set coordinate of other dataset (camera pose and lidar)?

### ISSUE THREAD

**Issue by LZL-CS** [rakhimovv/npbgpp#13]
Hi @rakhimovv @TArdelean, thanks for your excellent work. Now I want to reproduce your npbgpp on RobotCar Dataset, which gets lidar dataset, RGB images and camera pose (from IMUs) from a motion car with onboard sensors. I am curious about what kind of MetaShape is used to generate point clouds, and camera poses in your work.

Note I have tried to set the camera pose and point clouds from lidar to OpenGL coordinate, but the value of PSNR is quite low (around 5), so I doubt the coordinate is not right. I appreciate any help that you can provide!

**Comment by rakhimovv** [comment]
Hi @LZL-CS 

you can take a look e.g. at
https://github.com/rakhimovv/npbgpp/blob/main/npbgplusplus/data/colmap_scene.py
https://github.com/rakhimovv/npbgpp/blob/main/configs/datasets/colmap_one_scene.yaml

so one option e.g. is to convert to colmap format or some other presented in the repo
the other option - write your own dataset class

point cloud can stay the same - no modification is needed

Regarding the camera pose format:

so we know that `x_cam = R^T @ (x_world - camera_center) = R^T @ x_world + T`

regarding notation in the code:
```
R_col = R^T (_col stands for matrix-(column)vec multiplication)
R_row = R

as R_col = [u^T, v^T, w^T] = [
u.x, u.y, u.z,
v.x, v.y, v.z,
w.x, w.y, w.z,
]
(u, v, w) are camera x,y,z-axis
```

so how finally to make conversion:

in p3d the camera format is x-axis(=u) points left, y-axis(=v) points up and z-axis(=w) points out from the image plane.

so e.g. in colmap: x-axis points right, y-axis points bottom and z-axis points out from the image plane.

therefore you need change a sign only before u and v in R_col, we do this by following:
`R_col[:2, :] *= -1`
`R_col` also affects `T `as `T=-R_col@cam_center`, so we need to change `T` too:
`T[:2] *= -1`

so finally you need to compare the camera axis orientation in your dataset, compared it to p3d and change the signs of the certain axes if needed

**Comment by LZL-CS** [comment]
Thanks for your kind reply. I will try it.
