### ISSUE TITLE
Doubts in DTU data preprocessing

### ISSUE THREAD

**Issue by MadaraItachi123** [rakhimovv/npbgpp#2]
Hi,

Thanks for the wonderful work. I was going through the code and I have a problem understanding one preprocessing step.
In https://github.com/rakhimovv/npbgpp/blob/28fcf16c2e271058d9743586d4fc09b935905c59/npbgplusplus/data/dtu_scene.py#L88, I don't understand why the signs of the first and second rows have been inverted. I'd be grateful if you could help me understand this. 

Thanks in advance

**Comment by rakhimovv** [comment]
Hi  ! Thank you for interest!

so basically:
`  x_view = R_col @ (x - cam_center)  # x_view: (3, 1), R_col: (3, 3), x_world: (3, 1), cam_center: (3, 1) `

where 
```
        [u_x u_y u_z]
R_col = [v_x v_y v_z]
        [w_x w_y w_z]

R_row = R_col.T
```
and `u`, `v` and `w` represent `x`, `y` and `z` camera axis in world coordinates correspondingly.

The PyTorch3D coordinate system assumes `+X:left`, `+Y: up` and `+Z: from us to scene (right-handed)`,
while DTU assumes `+X: right`, `+Y: bottom` and +`Z: from us to scene  `.

Therefore we need to make the following changes: `u -> -u`, `v -> -v`
 and also we need to change `T` as `T = - R_col @ cam_center`

  i.e. we need to multiply the first two rows by -1.

**Comment by MadaraItachi123** [comment]
Ah, understood! Thanks for the quick response. Closing issue now.
