### ISSUE TITLE
Make datasets accessible

### ISSUE THREAD

**Issue by mhdadk** [rakhimovv/npbgpp#3]
Hi,

Thanks a lot for your contributions! Currently, the datasets provided are hosted on yandex.disk. However, it is not possible to download these datasets in bulk (clicking "download all" on yandex.disk), as a premium subscription to yandex.disk is required. To avoid this problem, could you possibly upload these datasets to a different data repository instead? Such as [Zenodo](https://zenodo.org/)? Licensing of the dataset is also possible on Zenodo. See this [repository](https://zenodo.org/record/5136592#.Yo5b6u7MLFg) for example.

**Comment by rakhimovv** [comment]
Hello, @mdabdk. Yes, as all files are too big to download from browser directly. Individual files (e.g. checkpoints) can be downloaded without any problem. We do not consider other options. Also files that we publish is not a Dataset, it's just some checkpoints and preprocessed files. Premium subscription is not required, you can download the data "in parts".
