### ISSUE TITLE
How to generate the point cloud of scannet scenes

### ISSUE THREAD

**Issue by Ru1zhi** [rakhimovv/npbgpp#4]
The paper mentions that the point clouds from the scannet dataset were reconstructed using depth maps following the NBPG setup. However, it seems that the [NPBG code for point cloud generation](https://github.com/alievk/npbg/blob/master/scripts/metashape_build_cloud.py) is only reconstructed by RGB, the scale and coordinate system of the reconstructed point clouds are not in the scannet world coordinate system. What do I need to do to generate a point cloud like the one in the example?

**Comment by TArdelean** [comment]
Hello,

We use a setup similar to NPBG for obtaining point clouds for Scannet using the available depth maps. The link you provided refers to the Npbg code for reconstructing point clouds for arbitrary scenes using Metashape on RGB images. As opposed to this, as mentioned in the paper, to obtain the point clouds for RGB-only scenes we use PatchmatchNet.
