### ISSUE TITLE
Reproducing the Results from the Paper

### ISSUE THREAD

**Issue by fhahlbohm** [rakhimovv/npbgpp#8]
Hey, I got two questions/requests.

1. I would like to reproduce the results from the paper for the 8 synthetic NeRF scenes. More precisely I need the 8 * 200 test images generated by NPBG++. I see that you provide checkpoints and instructions. As I want to avoid unnecessary work, I wanted to ask whether it would be possible to upload the images you used for the paper.
Alternatively, I would love a quick explanation of how to generate the results for the synthetic NeRF dataset from the provided checkpoints. Are there any configurations for the default commands that I should make to get the exact results?

2. I think support for the CO3D dataset would be a great addition. Have you considered adding it and if not, do you have any idea of how I could add support for the dataset myself? Specifically, I wonder how I would proceed if I wanted to optimize a NPBG++ model for a single scene of the CO3D dataset (CO3D contains around 50 object categories with hundreds of scenes each).

**Comment by rakhimovv** [comment]
Hello @fhahlbohm 

1. I uploaded the results to the cloud https://disk.yandex.ru/d/-1kx0XUlRHNumQ

Results are for hotdog,ficus,mic scenes. Others were used for pretraining.
If you need the results with per scene finetuning tell me.

Results were obtained with the followind command similar to what one can find in Readme:
`python train_net.py trainer.gpus=1 hydra.run.dir=test/npbgpp_nerf_mvs_ft_hotdog datasets=nerf_blender_one_scene datasets.scene_name=hotdog system=npbgpp_sphere system.visibility_scale=1.0 weights_path=checkpoints/npbgpp_nerf_mvs_ft_epoch23.ckpt eval_only=true dataloader=small`

2. Unfortunately I have no time for adding CO3D. You can add them similar to dataset classes already presented here 
https://github.com/rakhimovv/npbgpp/tree/main/npbgplusplus/data

**Comment by fhahlbohm** [comment]
Thank you very much! Exactly what I was looking for!
